Update 15-matrices.yaml

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -8,8 +8,15 @@ jobs:
         runs-on: ${{ matrix.OS }}
         strategy:
             matrix:
+                # within matrix, if one job failed, the others will be skipped or marked as failed, depending on the configuration; also we can specify the max number of parallel jobs to run
                 node-version: [18.x, 22.x, 24.x]
                 OS: [ubuntu-latest, windows-latest]
+                include:
+                    - node-version: 18.x
+                      OS: macos-latest
+                    - node-version: 24.x
+                      OS: ubuntu-latest
+                      tag: experimental
         steps:
             - name: Checkout Repository
               uses: actions/checkout@v5
@@ -18,5 +25,15 @@ jobs:
               uses: actions/setup-node@v3
               with:
                     node-version: ${{ matrix.node-version }}
+            - name: Fail if experimental version
+              if: matrix.tag == 'experimental'
+              run: exit 1
             - name: Perform Tests
-              run: echo "Running tests on Node.js version ${{ matrix.node-version }} on OS ${{ matrix.OS }}"
+              run: |
+                echo "Running tests on Node.js version ${{ matrix.node-version }} on OS ${{ matrix.OS }}"
+                sleep 10
+            - name: Upload test results
+              uses: actions/upload-artifact@v4
+              with:
+                  name: test-results-${{ matrix.node-version }}-${{ matrix.OS }}
+                  path: ${{ github.workspace }}
